from __future__ import annotations

AGENT_DEFAULT_MAX_RESUMES = 50
AGENT_DEFAULT_MAX_LIFETIME_HOURS = 720
AGENT_DEFAULT_MAX_TOTAL_TOKENS = 1_000_000
AGENT_DEFAULT_MAX_COST_EUR = 5.0

MAX_PROMPT_CHARS = 4000
