from . import common
from . import test_product_code_sequence
from . import test_product_code_automation
from . import test_product_code_uniqueness
from . import test_product_display_name_search
from . import test_product_price
from . import test_product_template
from . import test_product_search
from . import test_res_config_settings
from . import test_js
