from . import registry_mixin
from . import category
from . import service
from . import cookie
from . import geo_rule
from . import country_group
from . import observation
from . import consent
from . import website
from . import ir_http
from . import ir_qweb
from . import res_config_settings
