from __future__ import annotations

DEFAULT_ICON = 'folder'
ICONS = {
    'archive': 'archive',
    'area-chart': 'area_chart',
    'balance-scale': 'balance',
    'bank': 'account_balance',
    'bar-chart': 'bar_chart',
    'bolt': 'flash_on',
    'book': 'book',
    'bookmark': 'bookmark',
    'briefcase': 'work',
    'bug': 'bug_report',
    'building': 'business',
    'bullhorn': 'campaign',
    'calculator': 'calculate',
    'calendar': 'calendar_today',
    'calendar-plus': 'calendar_today',
    'camera': 'photo_camera',
    'car': 'directions_car',
    'check': 'check',
    'check-square': 'check_box',
    'clock': 'schedule',
    'cloud': 'cloud',
    'code': 'code',
    'coffee': 'coffee',
    'cog': 'settings',
    'cogs': 'settings',
    'comment': 'chat_bubble',
    'comments': 'forum',
    'credit-card': 'credit_card',
    'cube': 'deployed_code',
    'cubes': 'deployed_code',
    'cutlery': 'restaurant',
    'database': 'database',
    'desktop': 'desktop_windows',
    'dollar': 'attach_money',
    'edit': 'edit',
    'envelope': 'mail',
    'eur': 'euro',
    'exclamation-triangle': 'warning',
    'file': 'description',
    'file-text': 'description',
    'flag': 'flag',
    'flask': 'science',
    'folder': 'folder',
    'folder-open': 'folder_open',
    'futbol': 'sports_soccer',
    'gavel': 'gavel',
    'gear': 'settings',
    'gift': 'card_giftcard',
    'globe': 'public',
    'graduation-cap': 'school',
    'handshake': 'handshake',
    'heart': 'favorite',
    'home': 'home',
    'hospital': 'local_hospital',
    'hourglass': 'hourglass_top',
    'image': 'image',
    'inbox': 'inbox',
    'industry': 'factory',
    'info-circle': 'info',
    'institution': 'account_balance',
    'key': 'key',
    'language': 'translate',
    'laptop': 'laptop',
    'leaf': 'eco',
    'legal': 'gavel',
    'life-ring': 'support',
    'lightbulb': 'lightbulb',
    'line-chart': 'show_chart',
    'list': 'list_alt',
    'list-alt': 'list_alt',
    'lock': 'lock',
    'magic': 'wand_stars',
    'map': 'map',
    'map-marker': 'location_on',
    'medkit': 'medical_services',
    'mobile': 'smartphone',
    'money': 'payments',
    'music': 'music_note',
    'newspaper': 'newspaper',
    'paint-brush': 'brush',
    'paper-plane': 'send',
    'paw': 'pets',
    'pencil': 'edit',
    'phone': 'phone',
    'picture': 'image',
    'pie-chart': 'pie_chart',
    'plane': 'flight',
    'print': 'print',
    'puzzle-piece': 'extension',
    'reply': 'mail',
    'question-circle': 'help',
    'rocket': 'rocket_launch',
    'rss': 'rss_feed',
    'search': 'search',
    'server': 'dns',
    'share': 'share',
    'share-alt': 'share',
    'shield': 'security',
    'shopping-bag': 'shopping_bag',
    'shopping-cart': 'shopping_cart',
    'sitemap': 'account_tree',
    'sliders': 'tune',
    'sticky-note': 'description',
    'star': 'star',
    'suitcase': 'work',
    'tachometer': 'speed',
    'tag': 'label',
    'tags': 'sell',
    'tasks': 'checklist',
    'terminal': 'terminal',
    'th': 'grid_view',
    'th-large': 'grid_view',
    'thumbs-up': 'thumb_up',
    'ticket': 'confirmation_number',
    'trophy': 'trophy',
    'truck': 'local_shipping',
    'university': 'account_balance',
    'usd': 'attach_money',
    'user': 'person',
    'users': 'group',
    'video-camera': 'videocam',
    'warning': 'warning',
    'wrench': 'build',
}


def material_icon(icon: str, default: str = DEFAULT_ICON) -> str:
    """Return the Material Symbols name of a Font Awesome class.

    Outline variants map to their glyph, unknown classes to ``default``.
    """
    name = icon.rsplit(maxsplit=1)[-1].removeprefix('fa-').removesuffix('-o')
    return ICONS.get(name, default)
