MCP_SERVER_NAME = 'odoo-mcp-server'
MCP_SERVER_VERSION = '1.0.0'

JSONRPC_VERSION = '2.0'

JSONRPC_PARSE_ERROR = -32700
JSONRPC_INVALID_REQUEST = -32600
JSONRPC_METHOD_NOT_FOUND = -32601
JSONRPC_INVALID_PARAMS = -32602
JSONRPC_INTERNAL_ERROR = -32603

MCP_UNSUPPORTED_PROTOCOL_VERSION = -32022

MCP_CORS_REQUEST_HEADERS = (
    'authorization, content-type, accept, origin, '
    'mcp-session-id, mcp-protocol-version, last-event-id'
)

MCP_CORS_RESPONSE_HEADERS = 'mcp-session-id'
